#ifndef CONFIG_H
#define CONFIG_H

#define PROCESS_MANAGER_MAX_UMASK_SIZE            5
#define PROCESS_MANAGER_MAX_USER_SIZE             50
#define PROCESS_MANAGER_MAX_PROCESS_NAME          50
#define PROCESS_MANAGER_MAX_PROCESSES_COUNT       10
#define PROCESS_MANAGER_MAX_BUFFER_SIZE           256
#define PROCESS_MANAGER_MAX_CMD_SIZE              1024
#define PROCESS_MANAGER_MAX_LINE_SIZE             1024
#define PROCESS_MANAGER_MAX_PROCESSES             1000
#define PROCESS_MANAGER_UID_THRESHOLD             1000
#define PROCESS_MANAGER_MAX_SYSTEM_USERNAMES_NUM  17  
#define PROCESS_MANAGER_CPU_USAGE_THRESHOLD       60
#define PROCESS_MANAGER_MAX_EXPECTED_THREADS      100
#define PROCESS_MANAGER_MIN_EXPECTED_THREADS      1
#define PROCESS_MANAGER_LEGITIMATE_PPIDS_NUM      18
#define PROCESS_MANAGER_LEGITIMATE_PPIDS          0,1,10238,10241,10592,10613,10648,11913,11914,12070,12104,12118,12125,2,399,445,446,447
#define PROCESS_MANAGER_PROC_DIR                  "/proc"
#define LOG_FILE_PATH 							"data/log.txt"
#define PROCESS_MANAGER_CPU_USAGE_SCRIPT          "scripts/total_cpu_usage.sh"

#define SYSTEM_MAX_THREADS						8

#define CONFIG_WITH_EXECUTION_TIME			    1
#define CONFIG_WITH_LOGGING_FEATURE 			  1

#endif // CONFIG_H
